from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

EXPORT_FORMATS = ("srt", "vtt", "ass", "txt", "json")

CONTENT_MODES = {
    "bilingual": "双语（原文在上，译文在下）",
    "translation": "仅译文",
    "source": "仅原文",
}

DEFAULT_MIN_DURATION_MS = 500
DEFAULT_MAX_DURATION_MS = 7000

ASS_HEADER = """[Script Info]
; Generated by FiveLangTranslator v0.4.0-alpha.2
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Microsoft YaHei,54,&H00FFFFFF,&H000000FF,&H00101010,&H80000000,0,0,0,0,100,100,0,0,1,2,1,2,80,80,60,1
Style: Source,Microsoft YaHei,34,&H00C0C0C0,&H000000FF,&H00101010,&H80000000,0,0,0,0,100,100,0,0,1,1,0,2,80,80,60,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


@dataclass(slots=True)
class TimelineEntry:
    index: int
    start_ms: int
    end_ms: int
    source_text: str
    translated_text: str
    source_language: str
    target_language: str
    provider: str


def _split(ms: int) -> tuple[int, int, int, int]:
    value = max(0, int(ms))
    return value // 3_600_000, (value // 60_000) % 60, (value // 1000) % 60, value % 1000


def srt_timestamp(ms: int) -> str:
    hours, minutes, seconds, millis = _split(ms)
    return f"{hours:02}:{minutes:02}:{seconds:02},{millis:03}"


def vtt_timestamp(ms: int) -> str:
    hours, minutes, seconds, millis = _split(ms)
    return f"{hours:02}:{minutes:02}:{seconds:02}.{millis:03}"


def ass_timestamp(ms: int) -> str:
    hours, minutes, seconds, millis = _split(ms)
    return f"{hours:01}:{minutes:02}:{seconds:02}.{millis // 10:02}"


def clock_timestamp(ms: int) -> str:
    hours, minutes, seconds, _ = _split(ms)
    return f"{hours:02}:{minutes:02}:{seconds:02}"


def build_timeline(
    segments,
    min_duration_ms: int = DEFAULT_MIN_DURATION_MS,
    max_duration_ms: int = DEFAULT_MAX_DURATION_MS,
) -> list[TimelineEntry]:
    """Normalise stored segments into a monotonic, non-overlapping timeline."""
    ordered = sorted(segments, key=lambda item: (getattr(item, "start_ms", 0), getattr(item, "id", 0)))
    entries: list[TimelineEntry] = []
    previous_end = 0
    for segment in ordered:
        text = str(getattr(segment, "source_text", "") or "").strip()
        translation = str(getattr(segment, "translated_text", "") or "").strip()
        if not text and not translation:
            continue
        start = max(previous_end, int(getattr(segment, "start_ms", 0) or 0))
        end = int(getattr(segment, "end_ms", start) or start)
        if end <= start:
            end = start + min_duration_ms
        end = min(end, start + max_duration_ms)
        if end <= start:
            end = start + min_duration_ms
        entries.append(TimelineEntry(
            len(entries) + 1,
            start,
            end,
            text,
            translation,
            str(getattr(segment, "source_language", "auto")),
            str(getattr(segment, "target_language", "zh")),
            str(getattr(segment, "provider", "")),
        ))
        previous_end = end
    return entries


def entry_text(entry: TimelineEntry, content: str = "bilingual", separator: str = "\n") -> str:
    lines: list[str] = []
    if content in {"source", "bilingual"} and entry.source_text:
        lines.append(entry.source_text)
    if content in {"translation", "bilingual"} and entry.translated_text:
        lines.append(entry.translated_text)
    if not lines:
        lines.append(entry.source_text or entry.translated_text)
    return separator.join(line.replace("\r", " ").strip() for line in lines)


def to_srt(entries: list[TimelineEntry], content: str = "bilingual") -> str:
    blocks = []
    for entry in entries:
        blocks.append(
            f"{entry.index}\n{srt_timestamp(entry.start_ms)} --> {srt_timestamp(entry.end_ms)}\n"
            f"{entry_text(entry, content)}\n"
        )
    return "\n".join(blocks)


def to_vtt(entries: list[TimelineEntry], content: str = "bilingual") -> str:
    blocks = ["WEBVTT", ""]
    for entry in entries:
        blocks.append(
            f"{vtt_timestamp(entry.start_ms)} --> {vtt_timestamp(entry.end_ms)}\n"
            f"{entry_text(entry, content)}\n"
        )
    return "\n".join(blocks)


def to_ass(entries: list[TimelineEntry], content: str = "bilingual") -> str:
    lines = [ASS_HEADER]
    for entry in entries:
        text = entry_text(entry, content, separator="\\N")
        lines.append(
            f"Dialogue: 0,{ass_timestamp(entry.start_ms)},{ass_timestamp(entry.end_ms)},"
            f"Default,,0,0,0,,{text}"
        )
    return "\n".join(lines) + "\n"


def to_txt(entries: list[TimelineEntry], content: str = "bilingual") -> str:
    lines = []
    for entry in entries:
        stamp = clock_timestamp(entry.start_ms)
        text = entry_text(entry, content, separator="\n")
        lines.append(f"[{stamp}] {text}")
    return "\n".join(lines)


def to_json(entries: list[TimelineEntry], session=None, content: str = "bilingual") -> str:
    payload = {
        "generator": "FiveLangTranslator v0.4.0-alpha.2",
        "exported_at": datetime.now().isoformat(timespec="seconds"),
        "content": content,
        "session": None
        if session is None
        else {
            "id": getattr(session, "id", ""),
            "name": getattr(session, "name", ""),
            "source_type": getattr(session, "source_type", ""),
            "target_language": getattr(session, "target_language", ""),
            "translation_style": getattr(session, "translation_style", ""),
            "started_at": getattr(session, "started_at", 0),
            "ended_at": getattr(session, "ended_at", None),
        },
        "segments": [
            {
                "index": entry.index,
                "start_ms": entry.start_ms,
                "end_ms": entry.end_ms,
                "start": srt_timestamp(entry.start_ms),
                "end": srt_timestamp(entry.end_ms),
                "source_text": entry.source_text,
                "translated_text": entry.translated_text,
                "source_language": entry.source_language,
                "target_language": entry.target_language,
                "provider": entry.provider,
            }
            for entry in entries
        ],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def export_extension(fmt: str) -> str:
    mapping = {"srt": ".srt", "vtt": ".vtt", "ass": ".ass", "txt": ".txt", "json": ".json"}
    return mapping.get(str(fmt).lower(), ".txt")


def export_text(fmt: str, segments, session=None, content: str = "bilingual") -> str:
    entries = build_timeline(segments)
    fmt = str(fmt).lower()
    if fmt == "srt":
        return to_srt(entries, content)
    if fmt == "vtt":
        return to_vtt(entries, content)
    if fmt == "ass":
        return to_ass(entries, content)
    if fmt == "json":
        return to_json(entries, session, content)
    return to_txt(entries, content)


def suggest_filename(session, fmt: str) -> str:
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    base = str(getattr(session, "name", "") or "subtitles").strip() or "subtitles"
    safe = "".join(character if character not in '\\/:*?"<>|' else "_" for character in base)
    return f"{safe}-{stamp}{export_extension(fmt)}"


def write_export(destination: str | Path, fmt: str, segments, session=None, content: str = "bilingual") -> Path:
    path = Path(destination).expanduser()
    path.parent.mkdir(parents=True, exist_ok=True)
    text = export_text(fmt, segments, session, content)
    path.write_text(text, encoding="utf-8")
    return path
